services:
  - type: web
    name: ga-recommender-api
    runtime: python
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000